# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_controllers/ArmState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ArmState(genpy.Message):
  _md5sum = "1ec4005eded14deb32698c63aa479d03"
  _type = "lwr_controllers/ArmState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

string[] joint_name
float32[] est_ext_torques
geometry_msgs/Wrench est_ee_wrench
geometry_msgs/Wrench est_ee_wrench_base

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','joint_name','est_ext_torques','est_ee_wrench','est_ee_wrench_base']
  _slot_types = ['std_msgs/Header','string[]','float32[]','geometry_msgs/Wrench','geometry_msgs/Wrench']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,joint_name,est_ext_torques,est_ee_wrench,est_ee_wrench_base

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.joint_name is None:
        self.joint_name = []
      if self.est_ext_torques is None:
        self.est_ext_torques = []
      if self.est_ee_wrench is None:
        self.est_ee_wrench = geometry_msgs.msg.Wrench()
      if self.est_ee_wrench_base is None:
        self.est_ee_wrench_base = geometry_msgs.msg.Wrench()
    else:
      self.header = std_msgs.msg.Header()
      self.joint_name = []
      self.est_ext_torques = []
      self.est_ee_wrench = geometry_msgs.msg.Wrench()
      self.est_ee_wrench_base = geometry_msgs.msg.Wrench()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.joint_name)
      buff.write(_struct_I.pack(length))
      for val1 in self.joint_name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.est_ext_torques)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.est_ext_torques))
      _x = self
      buff.write(_get_struct_12d().pack(_x.est_ee_wrench.force.x, _x.est_ee_wrench.force.y, _x.est_ee_wrench.force.z, _x.est_ee_wrench.torque.x, _x.est_ee_wrench.torque.y, _x.est_ee_wrench.torque.z, _x.est_ee_wrench_base.force.x, _x.est_ee_wrench_base.force.y, _x.est_ee_wrench_base.force.z, _x.est_ee_wrench_base.torque.x, _x.est_ee_wrench_base.torque.y, _x.est_ee_wrench_base.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.est_ee_wrench is None:
        self.est_ee_wrench = geometry_msgs.msg.Wrench()
      if self.est_ee_wrench_base is None:
        self.est_ee_wrench_base = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.joint_name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.joint_name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.est_ext_torques = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 96
      (_x.est_ee_wrench.force.x, _x.est_ee_wrench.force.y, _x.est_ee_wrench.force.z, _x.est_ee_wrench.torque.x, _x.est_ee_wrench.torque.y, _x.est_ee_wrench.torque.z, _x.est_ee_wrench_base.force.x, _x.est_ee_wrench_base.force.y, _x.est_ee_wrench_base.force.z, _x.est_ee_wrench_base.torque.x, _x.est_ee_wrench_base.torque.y, _x.est_ee_wrench_base.torque.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.joint_name)
      buff.write(_struct_I.pack(length))
      for val1 in self.joint_name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.est_ext_torques)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.est_ext_torques.tostring())
      _x = self
      buff.write(_get_struct_12d().pack(_x.est_ee_wrench.force.x, _x.est_ee_wrench.force.y, _x.est_ee_wrench.force.z, _x.est_ee_wrench.torque.x, _x.est_ee_wrench.torque.y, _x.est_ee_wrench.torque.z, _x.est_ee_wrench_base.force.x, _x.est_ee_wrench_base.force.y, _x.est_ee_wrench_base.force.z, _x.est_ee_wrench_base.torque.x, _x.est_ee_wrench_base.torque.y, _x.est_ee_wrench_base.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.est_ee_wrench is None:
        self.est_ee_wrench = geometry_msgs.msg.Wrench()
      if self.est_ee_wrench_base is None:
        self.est_ee_wrench_base = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.joint_name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.joint_name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.est_ext_torques = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 96
      (_x.est_ee_wrench.force.x, _x.est_ee_wrench.force.y, _x.est_ee_wrench.force.z, _x.est_ee_wrench.torque.x, _x.est_ee_wrench.torque.y, _x.est_ee_wrench.torque.z, _x.est_ee_wrench_base.force.x, _x.est_ee_wrench_base.force.y, _x.est_ee_wrench_base.force.z, _x.est_ee_wrench_base.torque.x, _x.est_ee_wrench_base.torque.y, _x.est_ee_wrench_base.torque.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
