# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_controllers/PoseRPY.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lwr_controllers.msg
import geometry_msgs.msg

class PoseRPY(genpy.Message):
  _md5sum = "ac4defc6a342778de62991685c2a0dda"
  _type = "lwr_controllers/PoseRPY"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#include <lwr_controllers/RPY.h>

int32 id
geometry_msgs/Vector3 position
RPY orientation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: lwr_controllers/RPY
float64 roll
float64 pitch
float64 yaw
"""
  __slots__ = ['id','position','orientation']
  _slot_types = ['int32','geometry_msgs/Vector3','lwr_controllers/RPY']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseRPY, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = lwr_controllers.msg.RPY()
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Vector3()
      self.orientation = lwr_controllers.msg.RPY()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i6d().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.orientation.roll, _x.orientation.pitch, _x.orientation.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = lwr_controllers.msg.RPY()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.orientation.roll, _x.orientation.pitch, _x.orientation.yaw,) = _get_struct_i6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i6d().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.orientation.roll, _x.orientation.pitch, _x.orientation.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.orientation is None:
        self.orientation = lwr_controllers.msg.RPY()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.orientation.roll, _x.orientation.pitch, _x.orientation.yaw,) = _get_struct_i6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i6d = None
def _get_struct_i6d():
    global _struct_i6d
    if _struct_i6d is None:
        _struct_i6d = struct.Struct("<i6d")
    return _struct_i6d
