(cl:defpackage lwr_controllers-srv
  (:use )
  (:export
   "SETCARTESIANIMPEDANCECOMMAND"
   "<SETCARTESIANIMPEDANCECOMMAND-REQUEST>"
   "SETCARTESIANIMPEDANCECOMMAND-REQUEST"
   "<SETCARTESIANIMPEDANCECOMMAND-RESPONSE>"
   "SETCARTESIANIMPEDANCECOMMAND-RESPONSE"
  ))

