// Generated by gencpp from file lwr_controllers/SetCartesianImpedanceCommandResponse.msg
// DO NOT EDIT!


#ifndef LWR_CONTROLLERS_MESSAGE_SETCARTESIANIMPEDANCECOMMANDRESPONSE_H
#define LWR_CONTROLLERS_MESSAGE_SETCARTESIANIMPEDANCECOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lwr_controllers
{
template <class ContainerAllocator>
struct SetCartesianImpedanceCommandResponse_
{
  typedef SetCartesianImpedanceCommandResponse_<ContainerAllocator> Type;

  SetCartesianImpedanceCommandResponse_()
    {
    }
  SetCartesianImpedanceCommandResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCartesianImpedanceCommandResponse_

typedef ::lwr_controllers::SetCartesianImpedanceCommandResponse_<std::allocator<void> > SetCartesianImpedanceCommandResponse;

typedef boost::shared_ptr< ::lwr_controllers::SetCartesianImpedanceCommandResponse > SetCartesianImpedanceCommandResponsePtr;
typedef boost::shared_ptr< ::lwr_controllers::SetCartesianImpedanceCommandResponse const> SetCartesianImpedanceCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lwr_controllers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lwr_controllers': ['/home/shimin/ROS_Prgm_Prj/src/kuka-lwr-master/lwr_controllers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lwr_controllers/SetCartesianImpedanceCommandResponse";
  }

  static const char* value(const ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCartesianImpedanceCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lwr_controllers::SetCartesianImpedanceCommandResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LWR_CONTROLLERS_MESSAGE_SETCARTESIANIMPEDANCECOMMANDRESPONSE_H
