// Generated by gencpp from file lwr_controllers/Stiffness.msg
// DO NOT EDIT!


#ifndef LWR_CONTROLLERS_MESSAGE_STIFFNESS_H
#define LWR_CONTROLLERS_MESSAGE_STIFFNESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lwr_controllers
{
template <class ContainerAllocator>
struct Stiffness_
{
  typedef Stiffness_<ContainerAllocator> Type;

  Stiffness_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
    }
  Stiffness_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rx_type;
  _rx_type rx;

   typedef double _ry_type;
  _ry_type ry;

   typedef double _rz_type;
  _rz_type rz;





  typedef boost::shared_ptr< ::lwr_controllers::Stiffness_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lwr_controllers::Stiffness_<ContainerAllocator> const> ConstPtr;

}; // struct Stiffness_

typedef ::lwr_controllers::Stiffness_<std::allocator<void> > Stiffness;

typedef boost::shared_ptr< ::lwr_controllers::Stiffness > StiffnessPtr;
typedef boost::shared_ptr< ::lwr_controllers::Stiffness const> StiffnessConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lwr_controllers::Stiffness_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lwr_controllers::Stiffness_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lwr_controllers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lwr_controllers': ['/home/shimin/ROS_Prgm_Prj/src/kuka-lwr/lwr_controllers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lwr_controllers::Stiffness_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lwr_controllers::Stiffness_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_controllers::Stiffness_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_controllers::Stiffness_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_controllers::Stiffness_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_controllers::Stiffness_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lwr_controllers::Stiffness_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d995302418aa13534aa14fc9aeed94";
  }

  static const char* value(const ::lwr_controllers::Stiffness_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d995302418aa13ULL;
  static const uint64_t static_value2 = 0x534aa14fc9aeed94ULL;
};

template<class ContainerAllocator>
struct DataType< ::lwr_controllers::Stiffness_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lwr_controllers/Stiffness";
  }

  static const char* value(const ::lwr_controllers::Stiffness_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lwr_controllers::Stiffness_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents a diagonal Cartesian stiffness\n\
# It is motivated by the KDL class: http://people.mech.kuleuven.be/~rsmits/kdl/api/html/classKDL_1_1Stiffness.html\n\
# The conversion would be straight-forward, however, a generic 6D stiffness matrix would be desirable\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 rx\n\
float64 ry\n\
float64 rz\n\
";
  }

  static const char* value(const ::lwr_controllers::Stiffness_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lwr_controllers::Stiffness_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rx);
      stream.next(m.ry);
      stream.next(m.rz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stiffness_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lwr_controllers::Stiffness_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lwr_controllers::Stiffness_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "rx: ";
    Printer<double>::stream(s, indent + "  ", v.rx);
    s << indent << "ry: ";
    Printer<double>::stream(s, indent + "  ", v.ry);
    s << indent << "rz: ";
    Printer<double>::stream(s, indent + "  ", v.rz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LWR_CONTROLLERS_MESSAGE_STIFFNESS_H
