# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_controllers/SetCartesianImpedanceCommandRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lwr_controllers.msg
import geometry_msgs.msg
import std_msgs.msg

class SetCartesianImpedanceCommandRequest(genpy.Message):
  _md5sum = "cc36264319f44d204c2ace0744aa21ee"
  _type = "lwr_controllers/SetCartesianImpedanceCommandRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """lwr_controllers/CartesianImpedancePoint command

================================================================================
MSG: lwr_controllers/CartesianImpedancePoint
std_msgs/Header header
# 1. If frame_id in header is NOT EMPTY, then x_FRI is considered to be the pose w.r.t. that frame, so the increment w.r.t. the current tip pose will be computed internally (in the teach pendant is equivalent to select the Cartesian increments to be in the WORLD frame) 
# 2. If frame_id in header is EMPTY, then x_FRI is considered to be the pose w.r.t. to the current tip pose (in the teach pendant is equivalent to select the Cartesian increments to be in the TOOL frame)
# The increment (or offset) is x_FRI
geometry_msgs/Pose x_FRI
# The stiffness, damping and wrench are expressed in the current tip frame readed in the HWiface
lwr_controllers/Stiffness k_FRI
lwr_controllers/Stiffness d_FRI
geometry_msgs/Wrench f_FRI
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: lwr_controllers/Stiffness
# This represents a diagonal Cartesian stiffness
# It is motivated by the KDL class: http://people.mech.kuleuven.be/~rsmits/kdl/api/html/classKDL_1_1Stiffness.html
# The conversion would be straight-forward, however, a generic 6D stiffness matrix would be desirable

float64 x
float64 y
float64 z
float64 rx
float64 ry
float64 rz
================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['command']
  _slot_types = ['lwr_controllers/CartesianImpedancePoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetCartesianImpedanceCommandRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.command is None:
        self.command = lwr_controllers.msg.CartesianImpedancePoint()
    else:
      self.command = lwr_controllers.msg.CartesianImpedancePoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs))
      _x = self.command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_25d().pack(_x.command.x_FRI.position.x, _x.command.x_FRI.position.y, _x.command.x_FRI.position.z, _x.command.x_FRI.orientation.x, _x.command.x_FRI.orientation.y, _x.command.x_FRI.orientation.z, _x.command.x_FRI.orientation.w, _x.command.k_FRI.x, _x.command.k_FRI.y, _x.command.k_FRI.z, _x.command.k_FRI.rx, _x.command.k_FRI.ry, _x.command.k_FRI.rz, _x.command.d_FRI.x, _x.command.d_FRI.y, _x.command.d_FRI.z, _x.command.d_FRI.rx, _x.command.d_FRI.ry, _x.command.d_FRI.rz, _x.command.f_FRI.force.x, _x.command.f_FRI.force.y, _x.command.f_FRI.force.z, _x.command.f_FRI.torque.x, _x.command.f_FRI.torque.y, _x.command.f_FRI.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.command is None:
        self.command = lwr_controllers.msg.CartesianImpedancePoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 200
      (_x.command.x_FRI.position.x, _x.command.x_FRI.position.y, _x.command.x_FRI.position.z, _x.command.x_FRI.orientation.x, _x.command.x_FRI.orientation.y, _x.command.x_FRI.orientation.z, _x.command.x_FRI.orientation.w, _x.command.k_FRI.x, _x.command.k_FRI.y, _x.command.k_FRI.z, _x.command.k_FRI.rx, _x.command.k_FRI.ry, _x.command.k_FRI.rz, _x.command.d_FRI.x, _x.command.d_FRI.y, _x.command.d_FRI.z, _x.command.d_FRI.rx, _x.command.d_FRI.ry, _x.command.d_FRI.rz, _x.command.f_FRI.force.x, _x.command.f_FRI.force.y, _x.command.f_FRI.force.z, _x.command.f_FRI.torque.x, _x.command.f_FRI.torque.y, _x.command.f_FRI.torque.z,) = _get_struct_25d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs))
      _x = self.command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_25d().pack(_x.command.x_FRI.position.x, _x.command.x_FRI.position.y, _x.command.x_FRI.position.z, _x.command.x_FRI.orientation.x, _x.command.x_FRI.orientation.y, _x.command.x_FRI.orientation.z, _x.command.x_FRI.orientation.w, _x.command.k_FRI.x, _x.command.k_FRI.y, _x.command.k_FRI.z, _x.command.k_FRI.rx, _x.command.k_FRI.ry, _x.command.k_FRI.rz, _x.command.d_FRI.x, _x.command.d_FRI.y, _x.command.d_FRI.z, _x.command.d_FRI.rx, _x.command.d_FRI.ry, _x.command.d_FRI.rz, _x.command.f_FRI.force.x, _x.command.f_FRI.force.y, _x.command.f_FRI.force.z, _x.command.f_FRI.torque.x, _x.command.f_FRI.torque.y, _x.command.f_FRI.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.command is None:
        self.command = lwr_controllers.msg.CartesianImpedancePoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 200
      (_x.command.x_FRI.position.x, _x.command.x_FRI.position.y, _x.command.x_FRI.position.z, _x.command.x_FRI.orientation.x, _x.command.x_FRI.orientation.y, _x.command.x_FRI.orientation.z, _x.command.x_FRI.orientation.w, _x.command.k_FRI.x, _x.command.k_FRI.y, _x.command.k_FRI.z, _x.command.k_FRI.rx, _x.command.k_FRI.ry, _x.command.k_FRI.rz, _x.command.d_FRI.x, _x.command.d_FRI.y, _x.command.d_FRI.z, _x.command.d_FRI.rx, _x.command.d_FRI.ry, _x.command.d_FRI.rz, _x.command.f_FRI.force.x, _x.command.f_FRI.force.y, _x.command.f_FRI.force.z, _x.command.f_FRI.torque.x, _x.command.f_FRI.torque.y, _x.command.f_FRI.torque.z,) = _get_struct_25d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_25d = None
def _get_struct_25d():
    global _struct_25d
    if _struct_25d is None:
        _struct_25d = struct.Struct("<25d")
    return _struct_25d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_controllers/SetCartesianImpedanceCommandResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetCartesianImpedanceCommandResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "lwr_controllers/SetCartesianImpedanceCommandResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetCartesianImpedanceCommandResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class SetCartesianImpedanceCommand(object):
  _type          = 'lwr_controllers/SetCartesianImpedanceCommand'
  _md5sum = 'cc36264319f44d204c2ace0744aa21ee'
  _request_class  = SetCartesianImpedanceCommandRequest
  _response_class = SetCartesianImpedanceCommandResponse
